# -*- coding: utf-8 -*-
"""위클리 글로벌피어그룹4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpZbkTDh8JO4U8wLdiYqnOZ2_WbmzNN3
"""

import sys
import subprocess

# 로컬(Windows) 콘솔에서 이모지/한글 print가 cp949로 깨지지 않도록 UTF-8로 전환
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

# 📦 엑셀 엔진(xlsxwriter)이 없으면 자동으로 설치
try:
    import xlsxwriter
except ImportError:
    print("📦 xlsxwriter 패키지 자동 설치 중...")
    subprocess.check_call([sys.executable, "-m", "pip", "install", "xlsxwriter"])
    import xlsxwriter

import pandas as pd
import yfinance as yf
from datetime import datetime, timedelta
import numpy as np

# =========================================================================
# TARGET_COMPANIES 리스트 (조선, 해운사, 건설기계, 방산)
# =========================================================================
TARGET_COMPANIES = [
    {"industry": "조선", "category_sub": "조선사", "region": "한국", "name": "HD현대중공업", "ticker": "329180.KS"},
    {"industry": "조선", "category_sub": "조선사", "region": "한국", "name": "한화오션", "ticker": "042660.KS"},
    {"industry": "조선", "category_sub": "조선사", "region": "한국", "name": "삼성중공업", "ticker": "010140.KS"},
    {"industry": "조선", "category_sub": "조선사", "region": "한국", "name": "HD한국조선해양", "ticker": "009540.KS"},
    {"industry": "조선", "category_sub": "조선사", "region": "한국", "name": "대한조선", "ticker": "439260.KS"},
    {"industry": "조선", "category_sub": "조선사", "region": "한국", "name": "HJ중공업", "ticker": "097230.KS"},

    {"industry": "조선", "category_sub": "조선사", "region": "중국", "name": "중국선박공업(CSSC)", "ticker": "600150.SS"},
    {"industry": "조선", "category_sub": "조선사", "region": "중국", "name": "양지장", "ticker": "BS6.SI"},
    {"industry": "조선", "category_sub": "조선사", "region": "중국", "name": "대련조선", "ticker": "601989.SS"},
    {"industry": "조선", "category_sub": "조선사", "region": "중국", "name": "CSSC O&ME", "ticker": "0317.HK"},
    {"industry": "조선", "category_sub": "조선사", "region": "싱가포르", "name": "Seatrium", "ticker": "5E2.SI"},
    {"industry": "조선", "category_sub": "조선사", "region": "일본", "name": "미쓰비시 중공업", "ticker": "7011.T"},
    {"industry": "조선", "category_sub": "조선사", "region": "일본", "name": "가와사키 중공업", "ticker": "7012.T"},
    {"industry": "조선", "category_sub": "조선사", "region": "일본", "name": "IHI", "ticker": "7013.T"},
    {"industry": "조선", "category_sub": "조선사", "region": "일본", "name": "나이카이 조선", "ticker": "7018.T"},
    {"industry": "조선", "category_sub": "조선사", "region": "일본", "name": "미쓰이 E&S", "ticker": "7003.T"},
    {"industry": "조선", "category_sub": "조선사", "region": "이탈리아", "name": "Fincantieri", "ticker": "FCT.MI"},
    {"industry": "조선", "category_sub": "조선사", "region": "미국", "name": "Huntington Ingalls Industries", "ticker": "HII"},
    {"industry": "조선", "category_sub": "조선사", "region": "호주", "name": "Austal Limited", "ticker": "ASB.AX"},

    {"industry": "조선", "category_sub": "엔진/기자재", "region": "한국", "name": "HD현대마린솔루션", "ticker": "443060.KS"},
    {"industry": "조선", "category_sub": "엔진/기자재", "region": "한국", "name": "에스엔시스", "ticker": "0008Z0.KQ"},
    {"industry": "조선", "category_sub": "엔진/기자재", "region": "한국", "name": "HD현대마린엔진", "ticker": "071970.KS"},
    {"industry": "조선", "category_sub": "엔진/기자재", "region": "한국", "name": "한화엔진", "ticker": "082740.KS"},
    {"industry": "조선", "category_sub": "엔진/기자재", "region": "한국", "name": "STX엔진", "ticker": "077970.KS"},
    {"industry": "조선", "category_sub": "엔진/기자재", "region": "핀란드", "name": "바르질라(Wartsila)", "ticker": "WRT1V.HE"},
    {"industry": "조선", "category_sub": "엔진/기자재", "region": "한국", "name": "케이프", "ticker": "064820.KQ"},
    {"industry": "조선", "category_sub": "엔진/기자재", "region": "한국", "name": "인화정공", "ticker": "101930.KQ"},

    {"industry": "조선", "category_sub": "기자재", "region": "노르웨이", "name": "콩스버그 그루펜", "ticker": "KOG.OL"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "한국카본", "ticker": "017960.KS"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "동성화인텍", "ticker": "033500.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "세진중공업", "ticker": "075580.KS"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "현대힘스", "ticker": "460930.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "오리엔탈정공", "ticker": "014940.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "동방선기", "ticker": "099410.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "일승", "ticker": "333430.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "대양전기공업", "ticker": "108380.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "한라IMS", "ticker": "092460.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "성광벤드", "ticker": "014620.KQ"},
    {"industry": "조선", "category_sub": "기자재", "region": "한국", "name": "태광", "ticker": "023160.KQ"},

    {"industry": "해운사", "category_sub": "벌크", "region": "그리스", "name": "Star Bulk Carriers Corp", "ticker": "SBLK"},
    {"industry": "해운사", "category_sub": "벌크", "region": "노르웨이", "name": "Golden Ocean", "ticker": "GOGL"},
    {"industry": "해운사", "category_sub": "탱크", "region": "미국", "name": "Frontline", "ticker": "FRO"},
    {"industry": "해운사", "category_sub": "탱크", "region": "미국", "name": "Scorpio Tankers", "ticker": "STNG"},
    {"industry": "해운사", "category_sub": "컨테이너선", "region": "덴마크", "name": "Maersk", "ticker": "MAERSK-B.CO"},
    {"industry": "해운사", "category_sub": "컨테이너선", "region": "이스라엘", "name": "ZIM", "ticker": "ZIM"},
    {"industry": "해운사", "category_sub": "LNG", "region": "미국", "name": "Flex LNG", "ticker": "FLNG"},
    {"industry": "해운사", "category_sub": "LNG", "region": "미국", "name": "Golar LNG", "ticker": "GLNG"},
    {"industry": "해운사", "category_sub": "LPG", "region": "미국", "name": "Dorian LPG", "ticker": "LPG"},
    {"industry": "해운사", "category_sub": "LPG", "region": "미국", "name": "BW LPG", "ticker": "BWLP"},
    {"industry": "해운사", "category_sub": "RIG", "region": "스위스", "name": "Transocean", "ticker": "RIG"},
    {"industry": "해운사", "category_sub": "RIG", "region": "덴마크", "name": "Noble Corporation", "ticker": "NE"},
    {"industry": "해운사", "category_sub": "RIG", "region": "미국", "name": "Valaris", "ticker": "VAL"},
    {"industry": "해운사", "category_sub": "RIG", "region": "미국", "name": "Seadrill", "ticker": "SDRL"},
    {"industry": "해운사", "category_sub": "RIG", "region": "오슬로", "name": "Odfjell Drilling", "ticker": "ODL.OL"},
    {"industry": "해운사", "category_sub": "RIG", "region": "오슬로", "name": "Dolphin Drilling", "ticker": "DDRIL.OL"},

    {"industry": "건설기계", "category_sub": "건설기계", "region": "한국", "name": "HD건설기계", "ticker": "267270.KS"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "한국", "name": "두산밥캣", "ticker": "241560.KS"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "미국", "name": "CATERPILLAR(캐터필라)", "ticker": "CAT"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "일본", "name": "KOMATSU(고마쓰)", "ticker": "6301.T"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "일본", "name": "HITACHI CM(히타치건기)", "ticker": "6305.T"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "한국", "name": "대동", "ticker": "000490.KS"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "한국부품", "name": "진성티이씨", "ticker": "036890.KQ"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "한국부품", "name": "디와이파워", "ticker": "210540.KS"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "한국부품", "name": "대창단조", "ticker": "015230.KS"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "스톡홀롬", "name": "볼보(VOLVO)", "ticker": "VOLV-B.ST"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "중국-상해", "name": "삼일중공업", "ticker": "600031.SS"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "중국-선전", "name": "서공기계", "ticker": "000425.SZ"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "홍콩", "name": "중롄중커", "ticker": "1157.HK"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "중국-선전", "name": "류궁기계", "ticker": "000528.SZ"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "홍콩", "name": "론킹", "ticker": "3339.HK"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "미국", "name": "디어 앤 컴퍼니", "ticker": "DE"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "미국", "name": "CNH 인더스트리얼", "ticker": "CNH"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "일본", "name": "다케우치 제작소", "ticker": "6432.T"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "일본", "name": "SUMITOMO HI", "ticker": "6302.T"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "스톡홀롬", "name": "샌드빅", "ticker": "SAND.ST"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "미국", "name": "유나이티드 렌탈스", "ticker": "URI"},
    {"industry": "건설기계", "category_sub": "건설기계", "region": "미국", "name": "테렉스", "ticker": "TEX"},

    {"industry": "방산", "category_sub": "체계", "region": "한국", "name": "한국항공우주", "ticker": "047810.KS"},
    {"industry": "방산", "category_sub": "체계", "region": "한국", "name": "한화에어로스페이스", "ticker": "012450.KS"},
    {"industry": "방산", "category_sub": "체계", "region": "한국", "name": "LIG디펜스앤에어로스페이스", "ticker": "079550.KS"},
    {"industry": "방산", "category_sub": "체계", "region": "한국", "name": "한화시스템", "ticker": "272210.KS"},
    {"industry": "방산", "category_sub": "체계", "region": "한국", "name": "현대로템", "ticker": "064350.KS"},
    {"industry": "방산", "category_sub": "부체계", "region": "한국", "name": "엠앤씨솔루션", "ticker": "484870.KS"},
    {"industry": "방산", "category_sub": "부체계", "region": "한국", "name": "삼영컴텍", "ticker": "484590.KQ"},
    {"industry": "방산", "category_sub": "부체계", "region": "한국", "name": "웨이브일렉트로닉스", "ticker": "095270.KQ"},
    {"industry": "방산", "category_sub": "부체계", "region": "한국", "name": "아이쓰리시스템", "ticker": "214430.KQ"},
    {"industry": "방산", "category_sub": "항공", "region": "한국", "name": "켄코아에어로스페이스", "ticker": "274090.KQ"},
    {"industry": "방산", "category_sub": "우주", "region": "한국", "name": "인텔리안테크", "ticker": "189300.KQ"},
    {"industry": "방산", "category_sub": "우주", "region": "한국", "name": "쎄트렉아이", "ticker": "099320.KQ"},
    {"industry": "방산", "category_sub": "우주", "region": "한국", "name": "제노코", "ticker": "361390.KQ"},
    {"industry": "방산", "category_sub": "항공", "region": "미국", "name": "Boeing", "ticker": "BA"},
    {"industry": "방산", "category_sub": "체계", "region": "미국", "name": "LOCKHEED MARTIN", "ticker": "LMT"},
    {"industry": "방산", "category_sub": "체계", "region": "미국", "name": "Northrop grumann", "ticker": "NOC"},
    {"industry": "방산", "category_sub": "체계", "region": "미국", "name": "GENERAL DYNAMICS", "ticker": "GD"},
    {"industry": "방산", "category_sub": "체계", "region": "미국", "name": "L3Harris Technologies", "ticker": "LHX"},
    {"industry": "방산", "category_sub": "체계", "region": "미국", "name": "RTX", "ticker": "RTX"},
    {"industry": "방산", "category_sub": "체계", "region": "유럽", "name": "Thales", "ticker": "HO.PA"},
    {"industry": "방산", "category_sub": "체계", "region": "유럽", "name": "BAE Systems", "ticker": "BA.L"},
    {"industry": "방산", "category_sub": "체계", "region": "유럽", "name": "Rheinmetall", "ticker": "RHM.DE"},
    {"industry": "방산", "category_sub": "항공", "region": "유럽", "name": "Dassault Aviation", "ticker": "AM.PA"},
    {"industry": "방산", "category_sub": "항공", "region": "유럽", "name": "Airbus", "ticker": "AIR.PA"},
    {"industry": "방산", "category_sub": "항공", "region": "유럽", "name": "Leonardo", "ticker": "LDO.MI"},
    {"industry": "방산", "category_sub": "항공", "region": "유럽", "name": "Saab AB", "ticker": "SAAB-B.ST"},
    {"industry": "방산", "category_sub": "항공", "region": "유럽", "name": "Safran S.A.", "ticker": "SAF.PA"},
]

import os

# 환율 엑셀과 같은 자리(저장소 output/)에 떨어뜨려 GitHub에서 바로 내려받게 한다.
OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "output")
OUTPUT_FILE = os.path.join(OUTPUT_DIR, "글로벌_주가_변동률_모니터링_최종.xlsx")

# 3번 시트 차트에 표시할 종목 + 선 서식(사용자가 편집한 엑셀 차트에서 추출한 값)
INDEX_CHART_COMPANIES = [
    "HD현대중공업", "HD한국조선해양", "삼성중공업", "한화오션",
    "한화엔진", "HD현대마린엔진", "HD현대마린솔루션",
]
INDEX_CHART_STYLE = {
    "HD현대중공업":     {"color": "#D9D9D9", "width": 1.5},
    "HD한국조선해양":   {"color": "#9CC2E5", "width": 1.5},
    "삼성중공업":       {"color": "#AA875E", "width": 1.5},
    "한화오션":         {"color": "#000000", "width": 1.0},
    "한화엔진":         {"color": "#D2C0AA", "width": 1.0, "dash": "dash"},
    "HD현대마린엔진":   {"color": "#595959", "width": 1.5, "dash": "dash"},
    "HD현대마린솔루션": {"color": "#7F7F7F", "width": 1.0},
}

# 4번 시트 그룹 구성: 필요할 때 회사명만 추가/삭제하면 됩니다.
INDEX_GROUPS = {
    "한국 조선사": ["HD현대중공업", "한화오션", "삼성중공업", "HD한국조선해양", "대한조선", "HJ중공업"],
    "중국 조선사": ["중국선박공업(CSSC)", "양지장", "대련조선", "CSSC O&ME"],
    "일본 조선사": ["미쓰비시 중공업", "가와사키 중공업", "IHI", "나이카이 조선", "미쓰이 E&S"],
    "한국 엔진사": ["HD현대마린엔진", "한화엔진", "STX엔진"],
}

# 그룹 평균 차트 색상·선두께 (사용자가 편집한 엑셀 차트에서 추출한 값)
GROUP_CHART_COLORS = {
    "한국 조선사": "#AA875E",  # 황갈색
    "중국 조선사": "#000000",  # 검정
    "일본 조선사": "#818181",  # 회색
    "한국 엔진사": "#2A5CAA",  # 파랑
}
GROUP_CHART_WIDTHS = {
    "한국 조선사": 1.5,
    "중국 조선사": 1.5,
    "일본 조선사": 1.0,
    "한국 엔진사": 1.0,
}

# =========================================================================
# P-P(Peer-to-Peer) 시트: 두 기준일 사이 주가 등락 비교
#   ▶ 매주 이 두 날짜만 바꾸면 P-P 시트 F8/G8 및 전체 등락률이 재계산됩니다.
# =========================================================================
PP_DATE_START = datetime(2026, 4, 30)
PP_DATE_END = datetime(2026, 6, 24)
PP_CHANGE_LABEL = "변동률"  # H열 헤더

# P-P 시트에 표시할 종목(기업명 기준, 원본 큐레이션 101개·순서 유지).
# 여기 목록에 있고 데이터 수집에 성공한 종목만 P-P에 나옵니다. 빈 리스트([])면 전체 사용.
PP_COMPANIES = [
    "HD현대중공업", "한화오션", "삼성중공업",
    "HD한국조선해양", "대한조선", "HJ중공업",
    "중국선박공업(CSSC)", "양지장", "CSSC O&ME",
    "Seatrium", "미쓰비시 중공업", "가와사키 중공업",
    "IHI", "나이카이 조선", "미쓰이 E&S",
    "Fincantieri", "Huntington Ingalls Industries", "Austal Limited",
    "HD현대마린솔루션", "에스엔시스", "HD현대마린엔진",
    "한화엔진", "STX엔진", "바르질라(Wartsila)",
    "케이프", "인화정공", "콩스버그 그루펜",
    "한국카본", "동성화인텍", "세진중공업",
    "현대힘스", "오리엔탈정공", "동방선기",
    "일승", "대양전기공업", "한라IMS",
    "성광벤드", "태광", "Star Bulk Carriers Corp",
    "Frontline", "Scorpio Tankers", "ZIM",
    "Flex LNG", "Golar LNG", "Dorian LPG",
    "BW LPG", "Transocean", "Noble Corporation",
    "Valaris", "Seadrill", "Odfjell Drilling",
    "Dolphin Drilling", "HD건설기계", "두산밥캣",
    "CATERPILLAR(캐터필라)", "KOMATSU(고마쓰)", "HITACHI CM(히타치건기)",
    "대동", "진성티이씨", "디와이파워",
    "대창단조", "볼보(VOLVO)", "삼일중공업",
    "서공기계", "중롄중커", "류궁기계",
    "론킹", "디어 앤 컴퍼니", "CNH 인더스트리얼",
    "다케우치 제작소", "SUMITOMO HI", "샌드빅",
    "유나이티드 렌탈스", "테렉스", "한국항공우주",
    "한화에어로스페이스", "LIG디펜스앤에어로스페이스", "한화시스템",
    "현대로템", "엠앤씨솔루션", "삼영컴텍",
    "웨이브일렉트로닉스", "아이쓰리시스템", "켄코아에어로스페이스",
    "인텔리안테크", "쎄트렉아이", "제노코",
    "Boeing", "LOCKHEED MARTIN", "Northrop grumann",
    "GENERAL DYNAMICS", "L3Harris Technologies", "RTX",
    "Thales", "BAE Systems", "Rheinmetall",
    "Dassault Aviation", "Airbus", "Leonardo",
    "Saab AB", "Safran S.A.",
]

def main():
    print("📈 [1/4] 야후 파이낸스 데이터 수집 시작...")

    today = datetime.today()
    start_date = (today - timedelta(days=4*365)).strftime('%Y-%m-%d')
    end_date = (today + timedelta(days=1)).strftime('%Y-%m-%d')

    history_dict = {}
    dashboard_data = []
    exchange_rates_to_usd = {'USD': 1.0}

    for comp in TARGET_COMPANIES:
        ticker = comp["ticker"]
        name = comp["name"]
        ind = comp["industry"]
        c_sub = comp["category_sub"]
        reg = comp["region"]
        print(f"🚀 [{ind} > {c_sub} > {reg}] {name} ({ticker}) 수집 중...")

        try:
            stock = yf.Ticker(ticker)
            hist = stock.history(start=start_date, end=end_date)
            info = stock.info

            if hist.empty:
                print(f"⚠️ {name} 데이터 빈 값 발생. 건너뜁니다.")
                continue

            hist.index = pd.to_datetime(hist.index).tz_localize(None).normalize()
            hist = hist[~hist.index.duplicated(keep='last')]

            three_years_ago = hist.index[-1] - timedelta(days=3*365)
            hist_3y = hist.loc[hist.index >= three_years_ago]

            hist_col_name = f"{name}({ticker})"
            history_dict[hist_col_name] = hist_3y['Close']

            current_price = hist['Close'].iloc[-1]
            latest_date = hist.index[-1]

            raw_mc = info.get('marketCap')
            if not raw_mc or raw_mc == 0:
                shares = info.get('sharesOutstanding')
                price = info.get('currentPrice')
                if shares and price:
                    raw_mc = shares * price
                else:
                    raw_mc = 0

            currency = info.get('currency', 'USD')
            if not raw_mc or raw_mc == 0:
                mc_str = "N/A"
            else:
                if currency not in exchange_rates_to_usd:
                    try:
                        ex_ticker = f"{currency}USD=X"
                        ex_data = yf.Ticker(ex_ticker).history(period="1d")
                        if not ex_data.empty:
                            exchange_rates_to_usd[currency] = ex_data['Close'].iloc[-1]
                        else:
                            exchange_rates_to_usd[currency] = 1.0
                    except:
                        exchange_rates_to_usd[currency] = 1.0

                mc_usd = raw_mc * exchange_rates_to_usd[currency]
                val_in_billion_usd = mc_usd / 1_000_000_000
                mc_str = f"{val_in_billion_usd:,.2f}"

            def calculate_return(days_ago):
                target_date = latest_date - timedelta(days=days_ago)
                past_data = hist.loc[hist.index <= target_date]
                if past_data.empty: return None
                past_price = past_data['Close'].iloc[-1]
                return (current_price - past_price) / past_price

            ret_1w = calculate_return(7)
            ret_1m = calculate_return(30)
            ret_3m = calculate_return(91)
            ret_1y = calculate_return(365)
            ret_3y = calculate_return(365*3)

            # YTD: 전년도 마지막 거래일 종가 대비 (연초대비 수익률)
            year_start = datetime(latest_date.year, 1, 1)
            prev_year_data = hist.loc[hist.index < year_start]
            if prev_year_data.empty:
                ret_ytd = None  # 올해 상장 등으로 전년도 종가가 없으면 공란
            else:
                ytd_base = prev_year_data['Close'].iloc[-1]
                ret_ytd = (current_price - ytd_base) / ytd_base

            # 52주 고점대비: 현재가 / 최근 52주 최고가 - 1 (0=고점, 음수=고점 아래)
            one_year_ago = latest_date - timedelta(days=365)
            last_1y_close = hist.loc[hist.index >= one_year_ago, 'Close']
            high_52w = last_1y_close.max()
            off_52w_high = (current_price / high_52w - 1) if (high_52w and high_52w > 0) else None

            dashboard_data.append([
                ind, c_sub, reg, name, ticker, mc_str, ret_1w, ret_1m, ret_3m, ret_ytd, "", ret_1y, ret_3y, off_52w_high, hist_col_name
            ])

        except Exception as e:
            print(f"❌ {name} 처리 중 오류 발생: {e}")

    print("\n📊 [2/4] 수집된 데이터 통합 및 시트 구조화 작업 진행 중...")

    df_history_raw = pd.DataFrame(history_dict).sort_index()
    df_history = df_history_raw.copy()

    df_history.replace([np.inf, -np.inf], np.nan, inplace=True)
    df_history = df_history.ffill().bfill()
    df_history.index = df_history.index.date
    df_history.index.name = "날짜"

    display_columns = [
        "산업", "소분류", "지역", "기업명", "티커", "현 시총\n(십억달러)",
        "1W", "1M", "3M", "YTD", "1년 주가 추이", "1Y", "3Y", "52주 고점\n대비"
    ]

    df_dash = pd.DataFrame(dashboard_data, columns=display_columns + ["hist_col_name"])

    # 종목별 최신 거래일의 1년 전(또는 그 이전 가장 가까운 거래일)을 100으로 환산합니다.
    # 상장 후 1년이 지나지 않아 기준값이 없는 종목은 INDEX를 만들지 않습니다.
    index_series = {}
    for col in df_history_raw.columns:
        prices = df_history_raw[col].dropna()
        if prices.empty:
            continue
        cutoff = prices.index[-1] - timedelta(days=365)
        base_candidates = prices.loc[prices.index <= cutoff]
        if base_candidates.empty:
            continue
        base_date = base_candidates.index[-1]
        base_price = base_candidates.iloc[-1]
        index_series[col] = (prices.loc[prices.index >= base_date] / base_price) * 100

    df_index = pd.DataFrame(index_series).sort_index()
    df_index.index = df_index.index.date
    df_index.index.name = "날짜"

    # 국가별 휴장일 때문에 생긴 중간 결측값은 직전 거래일 INDEX로 채웁니다.
    # 단, 상장 전처럼 앞쪽에 연속된 결측값은 그대로 둡니다.
    index_holiday_mask = df_index.isna() & df_index.ffill().notna()
    df_index = df_index.ffill()

    name_to_hist_col = {
        row["기업명"]: row["hist_col_name"] for _, row in df_dash.iterrows()
    }
    group_index = {}
    for group_name, company_names in INDEX_GROUPS.items():
        member_cols = [name_to_hist_col[name] for name in company_names
                       if name in name_to_hist_col and name_to_hist_col[name] in df_index.columns]
        if member_cols:
            group_index[group_name] = df_index[member_cols].mean(axis=1, skipna=True)
    df_group_index = pd.DataFrame(group_index)
    df_group_index.index.name = "날짜"

    print("🎨 [3/4] 요청 레이아웃에 맞춰 대시보드 서식 디자인 및 색상 맵핑 중...")

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    with pd.ExcelWriter(OUTPUT_FILE, engine='xlsxwriter') as writer:
        df_history.to_excel(writer, sheet_name="주가데이터")
        # INDEX 2개 시트는 1행을 비워 그 위에 차트를 얹는다(startrow=1 → 헤더=2행, 데이터=3행부터)
        df_index.to_excel(writer, sheet_name="1년 INDEX", startrow=1)
        df_group_index.to_excel(writer, sheet_name="그룹 평균 INDEX", startrow=1)

        workbook = writer.book
        ws1 = writer.sheets["주가데이터"]
        ws2 = workbook.add_worksheet("상승률 대시보드")
        ws3 = writer.sheets["1년 INDEX"]
        ws4 = writer.sheets["그룹 평균 INDEX"]

        NAVY_DARK = '#1F4E79'
        GRAY_LIGHT = '#F2F2F2'
        BORDER_COLOR = '#D9D9D9'

        format_title = workbook.add_format({'font_name': 'Malgun Gothic', 'font_size': 16, 'bold': True, 'font_color': NAVY_DARK})
        format_header = workbook.add_format({
            'bg_color': NAVY_DARK, 'font_color': 'white', 'bold': True,
            'align': 'center', 'valign': 'vcenter', 'border': 1,
            'border_color': BORDER_COLOR, 'font_name': 'Malgun Gothic', 'font_size': 11,
            'text_wrap': True
        })

        format_top_label = workbook.add_format({
            'bg_color': NAVY_DARK, 'font_color': 'white', 'bold': True,
            'align': 'left', 'valign': 'vcenter', 'font_name': 'Malgun Gothic', 'font_size': 10
        })

        format_index_holiday = workbook.add_format({
            'bg_color': '#D9E1F2', 'font_color': '#666666',
            'num_format': '#,##0.0', 'font_name': 'Malgun Gothic',
            'font_size': 10
        })

        # 숫자 서식: 주가데이터(한국 #,##0 / 해외 #,##0.0), INDEX(#,##0.0)
        fmt_price_kr = workbook.add_format({'num_format': '#,##0'})
        fmt_price_ov = workbook.add_format({'num_format': '#,##0.0'})
        fmt_index_num = workbook.add_format({'num_format': '#,##0.0'})

        format_cache = {}
        def get_cell_format(bg_color, align, is_bold, num_format, font_color, top_b, bottom_b, left_b, right_b):
            key = (bg_color, align, is_bold, num_format, font_color, top_b, bottom_b, left_b, right_b)
            if key not in format_cache:
                fmt_dict = {
                    'bg_color': bg_color, 'align': align, 'valign': 'vcenter',
                    'top': top_b, 'bottom': bottom_b, 'left': left_b, 'right': right_b,
                    'top_color': BORDER_COLOR, 'bottom_color': BORDER_COLOR,
                    'left_color': BORDER_COLOR, 'right_color': BORDER_COLOR,
                    'font_name': 'Malgun Gothic', 'font_size': 10,
                    'bold': is_bold, 'font_color': font_color
                }
                if num_format: fmt_dict['num_format'] = num_format
                format_cache[key] = workbook.add_format(fmt_dict)
            return format_cache[key]

        ws2.merge_range('A2:N2', "🌐 글로벌 관측 섹터 주요 기업 주가 변동률 모니터링", format_title)

        def is_same_as_prev(r, c):
            if r == 0: return False
            for i in range(c + 1):
                if df_dash.iloc[r, i] != df_dash.iloc[r-1, i]: return False
            return True

        def is_same_as_next(r, c):
            if r == len(df_dash) - 1: return False
            for i in range(c + 1):
                if df_dash.iloc[r, i] != df_dash.iloc[r+1, i]: return False
            return True

        ws_row = 3
        current_industry = None

        # 📌 첫 번째 테이블인지 확인하는 스위치 변수
        is_first_table = True

        for row_idx in range(len(df_dash)):
            industry = df_dash.iloc[row_idx]["산업"]

            if industry != current_industry:
                if is_first_table:
                    # 📌 1. 제일 처음 등장하는 테이블(예: 조선)의 헤더는 접지 않음 (그대로 노출)
                    ws2.set_row(ws_row, 16)
                    ws2.merge_range(ws_row, 6, ws_row, 13, '상승률', format_top_label)
                    ws_row += 1

                    ws2.set_row(ws_row, 32)
                    for col_num, col_name in enumerate(display_columns):
                        ws2.write(ws_row, col_num, col_name, format_header)
                    ws_row += 1

                    is_first_table = False # 다음 산업부터는 접히도록 스위치 끄기
                else:
                    # 📌 2. 두 번째 산업(예: 해운사, 건설기계 등)부터는 헤더 행 숨김/접기 처리
                    ws2.set_row(ws_row, 16, None, {'level': 1, 'hidden': True})
                    ws2.merge_range(ws_row, 6, ws_row, 13, '상승률', format_top_label)
                    ws_row += 1

                    ws2.set_row(ws_row, 32, None, {'level': 1, 'hidden': True})
                    for col_num, col_name in enumerate(display_columns):
                        ws2.write(ws_row, col_num, col_name, format_header)
                    ws_row += 1

                current_industry = industry

            # 📌 주가 데이터 행은 접지 않음 (기본 노출)
            ws2.set_row(ws_row, 22)
            default_bg_color = GRAY_LIGHT if row_idx % 2 == 0 else '#FFFFFF'

            hist_col = df_dash.iloc[row_idx]["hist_col_name"]

            for col_idx in range(len(display_columns)):
                val = df_dash.iloc[row_idx, col_idx]
                if pd.isna(val) and col_idx != 10: val = ""

                align = 'center'
                bold = False
                num_fmt = None
                font_color = 'black'
                bg_color = default_bg_color

                top_border, bottom_border, left_border, right_border = 1, 1, 1, 1
                display_val = val

                if col_idx in [0, 1, 2]:
                    bg_color = '#FFFFFF'
                    same_prev = is_same_as_prev(row_idx, col_idx)
                    same_next = is_same_as_next(row_idx, col_idx)

                    if same_prev:
                        top_border = 0
                        display_val = ""
                    if same_next:
                        bottom_border = 0

                if col_idx in [1, 2, 4, 5, 10]: align = 'center'
                elif col_idx == 3:
                    align = 'left'
                    bold = True
                elif col_idx in [6, 7, 8, 9, 11, 12, 13]:
                    align = 'right'
                    num_fmt = '0.0%'
                    if isinstance(val, (int, float)):
                        if val > 0: font_color = '#C00000'
                        elif val < 0: font_color = '#0070C0'

                fmt = get_cell_format(bg_color, align, bold, num_fmt, font_color, top_border, bottom_border, left_border, right_border)

                if col_idx == 10:
                    ws2.write_blank(ws_row, col_idx, '', fmt)
                else:
                    ws2.write(ws_row, col_idx, display_val, fmt)

            if hist_col in df_history.columns:
                col_idx_hist = df_history.columns.get_loc(hist_col) + 1
                col_letter = xlsxwriter.utility.xl_col_to_name(col_idx_hist)
                max_row = len(df_history) + 1
                start_row = max(2, max_row - 251)

                ws2.add_sparkline(ws_row, 10, {
                    'range': f"'주가데이터'!{col_letter}{start_row}:{col_letter}{max_row}",
                    'type': 'line',
                    'style': 18,
                    'empty_cells': 'connect',
                    'high_point': True,
                    'low_point': True
                })

            ws_row += 1

        pct_cols = [6, 7, 8, 9, 11, 12, 13]
        for c in pct_cols:
            col_letter = xlsxwriter.utility.xl_col_to_name(c)
            ws2.conditional_format(f"{col_letter}4:{col_letter}{ws_row}", {
                'type': '2_color_scale',
                'min_color': '#FFFFFF',
                'max_color': '#FFC7CE'
            })

        ws2.set_column('A:A', 10)
        ws2.set_column('B:C', 12)
        ws2.set_column('D:D', 20)
        ws2.set_column('E:E', 12, None, {'level': 1, 'hidden': True})
        ws2.set_column('F:F', 12)
        ws2.set_column('G:J', 6)
        ws2.set_column('K:K', 20)
        ws2.set_column('L:M', 6)
        ws2.set_column('N:N', 9)

        ws1.set_column('A:A', 14)
        for i, col in enumerate(df_history.columns):
            ticker = col.rsplit("(", 1)[-1].rstrip(")")  # "이름(티커)" → 티커
            is_kr = ticker.endswith((".KS", ".KQ"))       # 한국거래소(KOSPI/KOSDAQ)
            ws1.set_column(i + 1, i + 1, 14, fmt_price_kr if is_kr else fmt_price_ov)

        # 3번 시트: 7개 주요 종목 INDEX 차트 (1행 비우고 상단에 배치)
        ws3.set_column('A:A', 14)
        ws3.set_column(1, max(1, len(df_index.columns)), 18, fmt_index_num)
        ws3.set_row(0, 195.75)          # 1행: 차트 자리(빈칸·고정 높이)
        ws3.freeze_panes(2, 1)          # 헤더(2행)까지 고정 → B3

        # 휴장일 보정 셀만 회색으로 표시(데이터가 3행부터이므로 start=2)
        for row_num, (_, mask_row) in enumerate(index_holiday_mask.iterrows(), start=2):
            for col_num, is_holiday in enumerate(mask_row, start=1):
                if is_holiday:
                    ws3.write_number(row_num, col_num, float(df_index.iloc[row_num - 2, col_num - 1]), format_index_holiday)

        chart3 = workbook.add_chart({'type': 'line'})
        idx_first, idx_last = 2, len(df_index) + 1   # 0-index: 데이터 3행~ = 2 ~ len+1
        for company_name in INDEX_CHART_COMPANIES:
            hist_col = name_to_hist_col.get(company_name)
            if hist_col in df_index.columns:
                col_num = df_index.columns.get_loc(hist_col) + 1
                st = INDEX_CHART_STYLE.get(company_name, {"color": "#7F7F7F", "width": 1.0})
                line = {'color': st['color'], 'width': st['width']}
                if st.get('dash'):
                    line['dash_type'] = st['dash']
                chart3.add_series({
                    'name': company_name,
                    'categories': ['1년 INDEX', idx_first, 0, idx_last, 0],
                    'values': ['1년 INDEX', idx_first, col_num, idx_last, col_num],
                    'line': line,
                })
        # 사용자 편집 서식: 제목없음 · X축 yy.mm 3개월 · Y축 격자숨김 · 범례 아래 · 흰 플롯영역
        chart3.set_x_axis({
            'date_axis': True, 'num_format': r'yy\.mm',
            'major_unit': 3, 'major_unit_type': 'months',
            'major_gridlines': {'visible': False},
            'line': {'color': '#7F7F7F', 'width': 0.75},
        })
        chart3.set_y_axis({
            'num_format': '#,##0',
            'major_gridlines': {'visible': False},
            'line': {'color': '#7F7F7F', 'width': 0.75},
        })
        chart3.set_legend({'position': 'bottom'})
        chart3.set_chartarea({'border': {'none': True}, 'fill': {'none': True}})
        chart3.set_plotarea({'fill': {'color': '#FFFFFF'}, 'border': {'none': True}})
        chart3.set_size({'width': 434, 'height': 208})
        ws3.insert_chart(0, 1, chart3)   # B1(1행)에 배치

        # 4번 시트: 그룹 평균 INDEX 차트 (1행 비우고 상단에 배치)
        ws4.set_column('A:A', 14)
        ws4.set_column(1, max(1, len(df_group_index.columns)), 18, fmt_index_num)
        ws4.set_row(0, 178.5)           # 1행: 차트 자리
        ws4.freeze_panes(2, 1)
        chart4 = workbook.add_chart({'type': 'line'})
        grp_first, grp_last = 2, len(df_group_index) + 1
        for group_name in df_group_index.columns:
            col_num = df_group_index.columns.get_loc(group_name) + 1
            chart4.add_series({
                'name': group_name,
                'categories': ['그룹 평균 INDEX', grp_first, 0, grp_last, 0],
                'values': ['그룹 평균 INDEX', grp_first, col_num, grp_last, col_num],
                'line': {
                    'color': GROUP_CHART_COLORS.get(group_name, '#666666'),
                    'width': GROUP_CHART_WIDTHS.get(group_name, 1.0),
                },
            })
        # 사용자 편집 서식: 제목없음 · 흰배경 · X축 yy.mm 3개월·라벨 아래 · Y축 80~300 20단위 · 범례 위
        chart4.set_chartarea({'border': {'none': True}, 'fill': {'none': True}})
        chart4.set_plotarea({'fill': {'color': '#FFFFFF'}, 'border': {'none': True}})
        chart4.set_x_axis({
            'date_axis': True,
            'num_format': r'yy\.mm',
            'major_unit': 3,
            'major_unit_type': 'months',
            'major_gridlines': {'visible': False},
            'line': {'color': '#7F7F7F', 'width': 0.75},
            'label_position': 'low',
        })
        chart4.set_y_axis({
            'min': 80,
            'max': 300,
            'major_unit': 20,
            'num_format': '#,##0',
            'major_gridlines': {'visible': False},
            'line': {'color': '#7F7F7F', 'width': 0.75},
        })
        chart4.set_legend({
            'position': 'top',
            'font': {'name': 'Malgun Gothic', 'size': 10, 'color': '#000000'},
        })
        chart4.set_size({'width': 434, 'height': 208})
        ws4.insert_chart(0, 1, chart4)

        # =====================================================================
        # 5번 시트: P-P (Peer-to-Peer) — 두 기준일 사이 등락 비교
        #   · '주가데이터' 시트를 VLOOKUP으로 참조 (정의된 이름 사용)
        #   · F8/G8 날짜를 바꾸면 전체가 재계산됨 (상단 PP_DATE_START/END)
        #   · 종목 목록/순서는 대시보드(df_dash)와 동일하게 자동 생성
        # =====================================================================
        ws5 = workbook.add_worksheet("P-P")

        # ▼ 정의된 이름(Named Range) 등록 -------------------------------------
        last_col_letter = xlsxwriter.utility.xl_col_to_name(len(df_history.columns))
        workbook.define_name("주가데이터", f"='주가데이터'!$A:${last_col_letter}")  # VLOOKUP 대상 표
        workbook.define_name("주가데이터H", "='주가데이터'!$1:$1")                    # MATCH 대상(종목키 행)

        pp_date_fmt = workbook.add_format({
            'bg_color': NAVY_DARK, 'font_color': 'white', 'bold': True,
            'align': 'center', 'valign': 'vcenter', 'num_format': 'yyyy-mm-dd',
            'font_name': 'Malgun Gothic', 'font_size': 10, 'border': 1, 'border_color': BORDER_COLOR
        })
        pp_num_fmt = workbook.add_format({
            'num_format': '#,##0', 'align': 'right', 'valign': 'vcenter',
            'font_name': 'Malgun Gothic', 'font_size': 10, 'border': 1, 'border_color': BORDER_COLOR
        })
        pp_pct_fmt = workbook.add_format({
            'num_format': '0.0%', 'align': 'right', 'valign': 'vcenter', 'bold': True,
            'font_name': 'Malgun Gothic', 'font_size': 10, 'border': 1, 'border_color': BORDER_COLOR
        })
        pp_text_fmt = workbook.add_format({
            'align': 'left', 'valign': 'vcenter',
            'font_name': 'Malgun Gothic', 'font_size': 10, 'border': 1, 'border_color': BORDER_COLOR
        })
        pp_center_fmt = workbook.add_format({
            'align': 'center', 'valign': 'vcenter',
            'font_name': 'Malgun Gothic', 'font_size': 10, 'border': 1, 'border_color': BORDER_COLOR
        })

        ws5.merge_range('A2:H2', "🔁 Peer-to-Peer 기간 등락 비교 (두 기준일 사이 주가 변동률)", format_title)
        ws5.write(5, 5, "※ F8·G8 날짜만 바꾸면 전체 재계산", format_top_label)

        # 헤더 (Excel 8행)
        HDR = 7  # 0-index → Excel 8행
        ws5.write(HDR, 0, "종목키", format_header)
        ws5.write(HDR, 1, "산업", format_header)
        ws5.write(HDR, 2, "소분류", format_header)
        ws5.write(HDR, 3, "지역", format_header)
        ws5.write(HDR, 4, "기업명", format_header)
        ws5.write_datetime(HDR, 5, PP_DATE_START, pp_date_fmt)
        ws5.write_datetime(HDR, 6, PP_DATE_END, pp_date_fmt)
        ws5.write(HDR, 7, PP_CHANGE_LABEL, format_header)

        # 데이터 (Excel 9행부터) — VLOOKUP은 정의된 이름 사용
        # PP_COMPANIES(큐레이션 목록)에 있고 수집 성공한 종목만, 목록 순서대로 표시.
        dash_by_name = {df_dash.iloc[i]["기업명"]: df_dash.iloc[i] for i in range(len(df_dash))}
        pp_names = PP_COMPANIES if PP_COMPANIES else list(dash_by_name.keys())
        pp_rows = [dash_by_name[nm] for nm in pp_names if nm in dash_by_name]
        for i, row in enumerate(pp_rows):
            r = HDR + 1 + i   # 0-index row
            xl = r + 1        # Excel 행번호
            ws5.write(r, 0, row["hist_col_name"], pp_text_fmt)
            ws5.write(r, 1, row["산업"], pp_center_fmt)
            ws5.write(r, 2, row["소분류"], pp_center_fmt)
            ws5.write(r, 3, row["지역"], pp_center_fmt)
            ws5.write(r, 4, row["기업명"], pp_text_fmt)
            ws5.write_formula(r, 5, f"=VLOOKUP(F$8,주가데이터,MATCH($A{xl},주가데이터H,0),0)", pp_num_fmt)
            ws5.write_formula(r, 6, f"=VLOOKUP(G$8,주가데이터,MATCH($A{xl},주가데이터H,0),0)", pp_num_fmt)
            ws5.write_formula(r, 7, f"=G{xl}/F{xl}-1", pp_pct_fmt)

        ws5.set_column('A:A', 32)
        ws5.set_column('B:B', 10)
        ws5.set_column('C:C', 12)
        ws5.set_column('D:D', 10)
        ws5.set_column('E:E', 23)
        ws5.set_column('F:G', 13)
        ws5.set_column('H:H', 12)
        ws5.freeze_panes(HDR + 1, 0)

    print(f"\n✨ [4/4] 성공! 생성된 파일: '{OUTPUT_FILE}'")

if __name__ == "__main__":
    main()

